### ISSUE TITLE
`Show in Explorer` shortcut not working for files with path length beyond `MAX_PATH`

### ISSUE THREAD

**Issue by Hrxn** [jdpurcell/qView#3] opened 2023-10-01 05:19 UTC
**Environment:**
- OS: Windows 10 22H2 19045.3516
- qView version: 2023-09-28.184c29f

**Information:**
I have set the `Show in Explorer` option in *Shortcuts* to a key (`W` in my case), but it does not show the currently opened file.
The Explorer does open, but simply in the default *This PC* view.

**Comment by jdpurcell** [comment] 2023-10-01 14:57
I cannot reproduce this under normal circumstances using the same Windows and qView version. It only happens if I delete the file outside of qView -> Show in Explorer -> and then of course Explorer cannot locate the file and stays in This PC view.

If you have any other details that may help reproduce this, let me know. Does it work in previous releases of this fork or in the official qView? Could it be related to certain characters in the file/folder name such as spaces, letters with umlauts, etc?

**Comment by Hrxn** [comment] 2023-10-01 15:09
Seems you're right..

Put some pictures with simple ASII only names in a nested directory, but low overall path name length, and it's working correctly in this case.

Okay, got to do some more tests first apparently, to see what actually caused this behaviour and if it can be reproduced reliably.

**Comment by Hrxn** [comment] 2023-10-02 01:30
I think I've found the culprit.

The total path length of an image where "Show in Explorer" wasn't working was 270 chars, so it's above the `MAX_PATH` limit of 260.

I've discarded this as a possibility at first, because I could obviously open and view those images, so I thought qView must support `LongPathsEnabled` (which works since Windows 10 v1607).

Apparently, "Show in Explorer" is a different case here..

**Comment by jdpurcell** [comment] 2023-10-02 02:38
Aha yeah I can reproduce it now. But it as far as I can tell the problem is on the Explorer side. qView simply runs this command for Show in Explorer:
`explorer /select, "C:\example.jpg"`
And it's indeed passing the full correct path there. If I run the same thing through the command prompt or a batch file it doesn't work either with anything longer than MAX_PATH. Interestingly the Windows Photos app is able to "Open in File Explorer" just fine, but I am guessing it's using a workaround. The same workaround I'll probably try, which is for really long paths, use the Windows API `GetShortPathNameW` to get the short (aka 8.3) version of the path before handing it to Explorer.

**Comment by Hrxn** [comment] 2023-10-02 02:40
> [..] Interestingly the Windows Photos app is able to "Open in File Explorer" just fine, but I am guessing it's using a workaround. [..]

Or it is using this:

> To specify an extended-length path, use the `"\\?\"` prefix

**Comment by jdpurcell** [comment] 2023-10-02 23:48
This is fixed in the latest release. I tried the extended-length path prefix by the way but it didn't help - Explorer seems to recognize the syntax and would open the folder properly for shorter paths, but it still failed with longer paths. So it's passing the short path to Explorer now if it was longer than MAX_PATH.

**Closed by jdpurcell** 2023-10-02 23:48 UTC
Labels: bug

**Comment by Hrxn** [comment] 2023-10-03 00:30
Okay, thanks! 😄

**Comment by Hrxn** [comment] 2023-10-12 12:06
I'm sorry to not have tested this earlier, but I didn't download the latest release until now.

The issue still persists for me, exactly as before. The changes you've made were good, and it is working, ostensibly, but I think there is a caveat here:

```cmd
C:\Users>fsutil 8dot3name
---- 8DOT3NAME Commands Supported ----

query   Query the current setting for the shortname behaviour on the system
scan    Scan for impacted registry entries
set     Change the setting that controls the shortname behavior on the system
strip   Remove the shortnames for all files within a directory

C:\Users>fsutil 8dot3name query
The registry state is: 1 (Disable 8dot3 name creation on all volumes).

C:\Users>
```

I assume it is working for you, because this 8dot3name option has not been set on your side.

Not sure how to proceed here... my knowledge about Qt is, well, I know what is is, and that's it already 😄

**Comment by jdpurcell** [comment] 2023-10-12 22:20
I believe Explorer's command line parser simply does not accept long paths via the /select switch. However, there is a Win32 API function `SHOpenFolderAndSelectItems` that seems to work for me even if 8.3 names are disabled. It is implemented in [this build](https://github.com/jdpurcell/qView/actions/runs/6501453138) if you'd like to try it.

**Comment by jdpurcell** [comment] 2023-10-13 22:50
Another note, in case someone discovers this issue in the future - even Visual Studio Code has the same problem with its "Reveal in File Explorer" feature, being unable to handle UNC paths >= 260 characters. It relies on Electron's `shell.showItemInFolder` method which is also using `SHOpenFolderAndSelectItems`.

I did find one more API for this purpose: WinRT's `Launcher.LaunchFolderAsync` or `Launcher.LaunchFolderPathAsync` methods, for which there is an overload accepting a `FolderLauncherOptions` parameter with an `ItemsToSelect` property. Perhaps that's how Microsoft Photos does it. I found [this code](https://github.com/equeim/tremotesf2/blob/master/src/filemanagerlauncher_windows.cpp) which is using it in a Qt application. I don't plan to try this myself, though.
